# Auto-labeling configuration

'area: core':
  - include/massive/core/**
  - src/massive/core/**

'area: rest':
  - include/massive/rest/**
  - src/massive/rest/**

'area: websocket':
  - include/massive/websocket/**
  - src/massive/websocket/**

'area: docs':
  - docs/**
  - '*.md'

'area: ci':
  - .github/workflows/**

'area: build':
  - CMakeLists.txt
  - CMakePresets.json
  - cmake/**

'type: bug':
  - '**/*bug*'
  - '**/*fix*'

'type: feature':
  - '**/*feature*'
  - '**/*enhancement*'

'type: documentation':
  - '**/*doc*'
  - '**/*readme*'

